[package]
name = "keepass-extract"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1"
keepass = "0.10"
rpassword = "7.4.0"
regex = "1"

[dev-dependencies]
assert_cmd = "2.2.0"
tempfile = "3.27.0"
predicates = "3.1"

[profile.release]
strip = true      # Removes debug symbols (the biggest bloat)
lto = true        # Link Time Optimization (removes unused code across crates)
codegen-units = 1 # Better optimization, slower compile
